# Generated by Django 6.1 on 2026-09-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome da Sala')),
                ('block', models.CharField(default='Bloco A', max_length=50)),
                ('capacity', models.IntegerField(default=40)),
                ('is_lab', models.BooleanField(default=False)),
                ('lab_type', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Sala / Espaço',
                'verbose_name_plural': 'Salas e Laboratórios',
            },
        ),
        migrations.CreateModel(
            name='ConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('is_hard', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=50, help_text='Peso da restrição (0 a 100)')),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Restrição',
                'verbose_name_plural': 'Configurações de Restrições',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Turno')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('code', models.CharField(max_length=10, verbose_name='Código / Sigla')),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('requires_lab', models.BooleanField(default=False, verbose_name='Requer Laboratório')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Professor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Institucional')),
                ('avatar_initials', models.CharField(default='DOC', max_length=5)),
                ('color', models.CharField(default='#1D4ED8', max_length=20)),
                ('max_weekly_hours', models.IntegerField(default=20, verbose_name='Carga Máx. Semanal (aulas)')),
                ('max_daily_hours', models.IntegerField(default=4, verbose_name='Máx. Aulas/Dia')),
                ('shift_preference', models.CharField(choices=[('ANY', 'Sem Restrição'), ('MORNING', 'Manhã (Preferencial)'), ('AFTERNOON', 'Tarde (Preferencial)'), ('NIGHT', 'Noite (Preferencial)')], default='ANY', max_length=20)),
                ('allow_double_lessons', models.BooleanField(default=True, verbose_name='Permitir Aulas Geminadas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Grade Horária Oficial 2026.1', max_length=100)),
                ('semester', models.CharField(default='1º Semestre 2026', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('viability_score', models.FloatField(default=100.0)),
                ('hard_violations_count', models.IntegerField(default=0)),
                ('soft_penalties_score', models.FloatField(default=0.0)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('algorithm_used', models.CharField(default='Genetic Algorithm + Tabu Search', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome da Turma')),
                ('grade_level', models.CharField(default='3º Ano Ensino Médio', max_length=80)),
                ('student_count', models.IntegerField(default=35)),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.shift')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordem do Período')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Slot')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('duration_minutes', models.IntegerField(default=50)),
                ('is_break', models.BooleanField(default=False, verbose_name='É Intervalo / Recreio')),
                ('allow_double_lesson', models.BooleanField(default=True)),
                ('requires_lab', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.shift')),
            ],
            options={
                'verbose_name': 'Slot de Tempo',
                'verbose_name_plural': 'Slots de Tempo',
                'ordering': ['shift', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_lessons', models.IntegerField(default=4, verbose_name='Aulas Semanais')),
                ('double_lessons_allowed', models.BooleanField(default=True)),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Carga Curricular',
                'verbose_name_plural': 'Cargas Curriculares',
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')])),
                ('status', models.CharField(choices=[('FREE', 'Livre / Disponível'), ('PREFERENTIAL', 'Preferencial'), ('BLOCKED', 'Bloqueio Absoluto (Hard Constraint)')], default='FREE', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot')),
            ],
            options={
                'verbose_name': 'Disponibilidade Docente',
                'verbose_name_plural': 'Disponibilidades Docentes',
                'unique_together': {('teacher', 'day_of_week', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')])),
                ('is_manual_override', models.BooleanField(default=False)),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, max_length=50, null=True)),
                ('conflict_message', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot')),
                ('timetable_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.timetableschedule')),
            ],
            options={
                'verbose_name': 'Alocação de Aula',
                'verbose_name_plural': 'Alocações de Aulas',
                'unique_together': {('timetable_schedule', 'school_class', 'day_of_week', 'time_slot')},
            },
        ),
    ]
