# Generated by Django 5.2.17 on 2026-09-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslotassignment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='curriculumrequirement',
            name='preferred_room',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='default_room',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
